- hosts: local
  connection: local
  vars:
    pip_install_packages:
      - name: docker
    ansible_distribution: ubuntu
    ansible_distribution_release: bionic
    docker_users:
      - "rich"
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
