---
- hosts: local
  connection: local
  tasks:
  - name: get confluent
    git:
      repo: https://github.com/confluentinc/examples
      dest: examples
      version: 5.3.1-post

  - name: Start it up
    docker_compose:
      project_src: examples/cp-all-in-one
      debug: yes
      build: yes
